### ISSUE TITLE
Cannot start drush

### ISSUE THREAD

**Issue by peschee** [Mogtofu33/docker-compose-drupal#1]
I downloaded the contents of the repository and wanted to test out a simple installation with Drupal + MySQL (MariaDB). I have only those two services activated in my docker compose file. The containers start up just fine. However, I wasn't able to install Drupal using drush. Running

`. scripts/start-drush.sh`

returns

`./scripts/start-drush.sh:13: = not found`

Any ideas?

**Comment by Mogtofu33** [comment]
Not sure about this error, I fixed the script, if you can test the last version.

**Comment by peschee** [comment]
Just tried again, same problem. I'm using the zsh shell. Do you think that might be an issue?

**Comment by Mogtofu33** [comment]
Not sure, but it can be related, my script is not marked for bash, I will fix it.
This script is just an helper to create an alias for the drush command to be run on the docker container.
`alias drush="docker exec --user apache:apache --interactive DK_CONTAINER drush @d"`

You have to replace DK_CONTAINER by the name of the container as a result from the command `docker ps`.

To revert it:  `unalias drush`
