### ISSUE TITLE
dcd-php error

### ISSUE THREAD

**Issue by bitcoin-australia** [Mogtofu33/docker-compose-drupal#6]
There is a problem with the site directory. There is no volume for the the following image:

image: mogtofu33/php:${PHP_VERSION:-7.2}
volumes:
   - /var/run/docker.sock:/var/run/docker.sock

**Comment by ashley-boardman** [comment]
this issue was reported here: https://github.com/docker/for-win/issues/1829#issuecomment-376328022

**Comment by Mogtofu33** [comment]
Are you on Mac or Windows ?

If you are on Windows there could be a problem with docker-compose, see [this issue](https://github.com/docker/for-win/issues/1829), depending how you launch docker-compose you could have to set `COMPOSE_CONVERT_WINDOWS_PATHS`, different options are listed in the issue.
