### ISSUE TITLE
Drush commands that require input hang

### ISSUE THREAD

**Issue by xurizaemon** [Mogtofu33/docker-compose-drupal#7]
Drush commands that require user input can hang after prompting.

    +------------+------------------------------------------------+-----------+
    | Collection | Config                                         | Operation |
    +------------+------------------------------------------------+-----------+
    |            | node.settings                                  | Update    |
    |            | core.entity_form_display.node.resource.default | Update    |
    |            | search_api.index.default_index                 | Update    |
    |            | core.entity_view_display.user.user.default     | Update    |
    |            | core.entity_view_display.node.resource.default | Update    |
    |            | core.entity_form_display.user.user.default     | Update    |
    |            | user.role.commenter                            | Update    |
    |            | user.role.editor                               | Update    |
    |            | filter.format.filtered_html                    | Update    |
    |            | filter.format.full_html                        | Update    |
    +------------+------------------------------------------------+-----------+

     Import the listed configuration changes? (yes/no) [yes]:
     > no
    ^C

I suspect this is because the [drush wrapper](https://github.com/Mogtofu33/docker-compose-drupal/blob/ca19d1b6e744f15709e171561277e35460c28d79/scripts/drush#L23) uses [_docker_exec_noi](https://github.com/Mogtofu33/docker-compose-drupal/blob/364a83ab6cd3220ce0a1d9a57343fcdc740c2026/scripts/helpers/common.sh#L126).

What do you think about switching it to use `docker_exec` instead, which adds --interactive? I'm guessing that the `_noi` means no-interactive and there's a reason we use that here, but there's other variation between `docker_exec` and `docker_exec_noi` which means they don't just swap out. (`docker_exec` needs `"${PROJECT_CONTAINER_NAME}"` as well to function.)

**Comment by Mogtofu33** [comment]
Fixed ;)
